# Install brew stuff without having to think about it.
#
# Paul Stevens <15 April 2019>

tap "caskroom/cask"
tap "caskroom/versions"
tap "johanhaleby/kubetail"
tap "homebrew/cask"

# Install apps to default /Applications directory
cask_args appdir: '/Applications'

# Casks
cask "adobe-acrobat-reader"
cask "cpuinfo"
cask "diffmerge"
cask "firefox"
cask "chef/chef/inspec"
cask "iterm2"
cask "java8"
cask "java11"
cask "java"
cask "spotify"
cask "vagrant"
cask "visual-studio-code"
cask "wireshark"

# Taps
tap "johanhaleby/kubetail"

# Brews
brew "ansible"
brew "awscli"
brew "curl-openssl"
brew "doctl"
brew "faas-cli"
brew "gcc"
brew "git"
brew "go"
brew "gradle"
brew "hub"
brew "hugo"
brew "jfrog-cli-go"
brew "jq"
brew "kotlin"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "kubetail"
brew "nmap"
brew "node"
brew "openssl"
brew "packer"
brew "pyenv"
brew "pyenv-virtualenv"
brew "pyenv-virtualenvwrapper"
brew "python"
brew "rbenv"
brew "repo"
brew "scala"
brew "sqlite"
brew "stern"
brew "terraform"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "yarn"
brew "zlib"
brew "zsh"
brew "zsh-completions"
